
# garak configuration file
#
# command line options override config file options
#
# all options are commented out by default
#
# Ref: https://reference.garak.ai/en/latest/configurable.html

# -----------------------------
# List of proble to choose from
# -----------------------------
# probe_spec: "ansiescape,\
#   av_spam_scanning,\
#   continuation,\
#   dan,\
#   divergence,\
#   doctor,\
#   donotanswer,\
#   dra,\
#   encoding,\
#   exploitation,\
#   fitd,\
#   glitch,\
#   goodside,\
#   grandma,\
#   latentinjection,\
#   leakreplay,\
#   misleading,\
#   packagehallucination,\
#   phrasing,\
#   promptinject,\
#   sata,\
#   snowball,\
#   topic,\
#   web_injection"
# -----------------------------

plugins:
  target_type: "function"
  target_name: "integrate#generate"
  probe_spec: "exploitation"

reporting:
  report_prefix: "reports/GenAI-Red-Team"
  taxonomy: "owasp"
